#!/bin/bash

# for colored output
BOLD="\e[1m"
RED="\e[31m"
GREEN="\e[32m"
BLUE="\e[34m"
YELLOW="\e[33m"
RESET="\e[0m"

cd ..

# read environment from args
ENVIRONMENT=$1
if [[ "$ENVIRONMENT" != "staging" && "$ENVIRONMENT" != "prod" ]]; then
  echo -e "${BOLD}${RED}Usage: ./deploy.sh [staging|production]${RESET}"
  exit 1
fi

# confirm environment for deployment
echo -e "${BOLD}${YELLOW}=====> DEPLOYING TO ${ENVIRONMENT} <=====${RESET}"
read -rp "Continue? (y/N) " confirm
if [[ "$confirm" =~ ^[Yy]$ ]]; then
  echo -e "${BOLD}${BLUE}Deploying to ${ENVIRONMENT}...${RESET}"
else
  echo "Aborted."
  exit 1
fi

# create temp-deploy if not exists, empty it if it does
if [ ! -d "temp-deploy" ]; then
	mkdir temp-deploy
else
	rm -rf temp-deploy/*
fi

# build ui based on environment
echo -e "${BOLD}${GREEN}Building ui for ${ENVIRONMENT}..."
cd ./desert-dice-ui && yarn build:$ENVIRONMENT && cd ..

# copy local api files to temp-deploy
echo "Copying api to temp deploy folder..."
cp -R ./desert-dice-api/src/* ./temp-deploy/.
cp ./desert-dice-api/app.js ./temp-deploy/
sed -i 's|\.\/src\/|.\/|g' ./temp-deploy/app.js # update module paths 
cp ./desert-dice-api/.env.$ENVIRONMENT ./temp-deploy/.env
cp ./desert-dice-api/package.json ./temp-deploy/.

# copy site files from local to remote
echo -e "${BOLD}${BLUE}Copying files to server...${RESET}"
rsync -avz -e "ssh -i ~/.ssh/ssh_hetzner" ./temp-deploy/ ttosi@5.78.41.98:~/sites/desertdiceco.com/$ENVIRONMENT
rsync -avz -e "ssh -i ~/.ssh/ssh_hetzner" ./desert-dice-api/public/ ttosi@5.78.41.98:~/sites/desertdiceco.com/$ENVIRONMENT/public

# install node modules
echo -e "${BOLD}${BLUE}Installing node modules on server...${RESET}"
ssh -i ~/.ssh/ssh_hetzner ttosi@5.78.41.98 "cd ~/sites/desertdiceco.com/"$ENVIRONMENT " && npm i"

# start or restart pm2 instance
if ssh -i ~/.ssh/ssh_hetzner ttosi@5.78.41.98 "pm2 show desertdice-${ENVIRONMENT} 2>&1 | grep doesn\'t"; then
  echo -e "${BOLD}${BLUE}Installing ${ENVIRONMENT} pm2 instance...${RESET}"
  ssh -i ~/.ssh/ssh_hetzner ttosi@5.78.41.98 "mkdir -p ~/sites/desertdiceco.com/${ENVIRONMENT}/logs"
  ssh -i ~/.ssh/ssh_hetzner ttosi@5.78.41.98 "pm2 start ~/sites/desertdiceco.com/${ENVIRONMENT}/app.js --name desertdice-${ENVIRONMENT} --output ~/sites/desertdiceco.com/${ENVIRONMENT}/logs/out.log --error ~/sites/desertdiceco.com/$ENVIRONMENT/logs/err.log && pm2 save"
else
  echo -e "${BOLD}${BLUE}Restarting ${ENVIRONMENT} pm2 instance...${RESET}"
  ssh -i ~/.ssh/ssh_hetzner ttosi@5.78.41.98 "pm2 restart desertdice-${ENVIRONMENT}"
fi

echo -e "${BOLD}${YELLOW}Removing temp-deploy dir...${RESET}"
rm -rf ./temp-deploy

echo -e "${BOLD}${GREEN}Successfully published to ${ENVIRONMENT}.${RESET}"